### ISSUE TITLE
No longer works after December 13th update

### ISSUE THREAD

**Issue by 1337Walrus** [adm244/Dishonored-MissionStats#2]
Self explanatory - judging by the [steamdb info,](https://steamdb.info/patchnotes/8335061/), it would appear the biggest change is the addition of libcurl.dll as well as minor changes to dishonored.exe itself. Launching the game with this mod installed now causes a fatal error on the title screen.

To reproduce:
1. Install mod.
2. Launch game through Steam. To see the fatal error log, you must run the game with the -windowed launch option, else the game will just immediately crash to desktop.

I've included a picture of said fatal error log.
![image](https://user-images.githubusercontent.com/93822595/207446515-4c047c4f-af49-42dd-89d8-7e3e314454cb.png)

**Comment by adm244** [comment]
I'll look into it. Thank you for reporting this issue.

Btw, Dishonored RHCP doesn't seem to have been updated (yet). If you can get access to it you could just copy "Dishonored.exe" from there and it should, although temporarily, fix it.

**Comment by adm244** [comment]
Here's a quick update: [Mission Stats v1.1 (Update13 Hotfix)](https://github.com/adm244/Dishonored-MissionStats/releases/tag/v1.1_hotfix)
This should fix all issues related to update13.

**Comment by adm244** [comment]
It looks like there are no problems with the hotfix (reported at least). This issue is now closed.
