### ISSUE TITLE
Turkish translation done!

### ISSUE THREAD

**Issue by DryreL** [adm244/Dishonored-MissionStats#4]
![d1](https://github.com/user-attachments/assets/a22d29e5-6fba-4111-a6f3-25d466815c2d)

Oyun duraklatma menüsüne "İstatistikler" butonu ekleyen yerel bir mod, böylece görev ortasında istatistikleri kontrol etmek mümkündür.

### **[[ÇEVİRİYİ İNDİRMEK İÇİN TIKLAYIN!]](https://www.nexusmods.com/dishonored/mods/117)**

**Comment by adm244** [comment]
Thanks!

**Comment by DryreL** [comment]
You're welcome :)
